[package]
name = "laria_vm"
description = "The Laria virtual machine"
license = "MIT"
version = "0.1.0"
authors = ["Ruby Lazuli <nipkraps@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
byteorder = "1.3.4"
num-derive = "0.3.3"
num-traits = "0.2.14"
thiserror = "1.0.21"
