[package]
name = "laria_log"
description = "Simple logging for Laria"
license = "MIT"
version = "0.1.0"
authors = ["Ruby Lazuli <nipkraps@gmail.com>"]
edition = "2018"

[dependencies]
colorful = "0.2.1"
